{% set name = "maps-cli" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maps-cli-{{ version }}.tar.gz
  sha256: 111e7775f632a917cf51802221810520c40711a2d745a8516610390e4270ac56

build:
  number: 1
  noarch: python
  entry_points:
    - maps = maps.commands:maps
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.1.4
  run:
    - click >=7.1.2,<8.0.0
    - geojson >=2.5.0,<3.0.0
    - geojsonio >=0.0.3,<0.0.4
    - geopy >=2.1.0,<3.0.0
    - here-location-services >=0.1.0,<0.2.0
    - overpy >=0.4,<0.5
    - python >={{ python_min }},<4.0
    - requests >=2.25.1,<3.0.0
    - simplejson >=3.17.2,<4.0.0

test:
  imports:
    - maps
    - maps.apis
  commands:
    - pip check
    - maps --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sackh/maps-cli
  summary: A CLI for maps services.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sackh
